import type { Alternative, MetricAssessment, Product } from "~/lib/domain/types";

const reviewedOn = "2026-03-14";
type LegacyProduct = Omit<Product, "disruptionConceptSlugs" | "maybeDisruptionException">;

function metric(
  value: number,
  rationale: string,
  sourceIds: string[],
  confidence: MetricAssessment["confidence"] = "medium",
): MetricAssessment {
  return {
    value,
    rationale,
    sourceIds,
    confidence,
    lastReviewedOn: reviewedOn,
  };
}

const rawProducts: LegacyProduct[] = [
  {
    slug: "nvidia-cuda",
    companySlug: "nvidia",
    name: "CUDA platform",
    category: "Developer platform",
    homepageUrl: "https://developer.nvidia.com/cuda-zone",
    summary: "NVIDIA's software stack for GPU programming and ecosystem lock-in.",
    whyItMatters:
      "CUDA is the software layer that turns hardware leadership into recurring ecosystem gravity.",
    replacementSketch: [
      "Portable compute stacks reduce lock-in by making AI workloads less dependent on one vendor's APIs.",
      "Decentralized GPU marketplaces can shift some value from proprietary platform control toward open capacity brokering.",
    ],
    alternativeSlugs: ["rocm", "akash-network"],
    sourceIds: ["nvidia-cuda", "amd-rocm", "akash"],
    technologyWaveIds: ["printed-electronics", "bitcoin-native-coordination"],
  },
  {
    slug: "nvidia-dgx",
    companySlug: "nvidia",
    name: "DGX and data-center systems",
    category: "AI infrastructure",
    homepageUrl: "https://www.nvidia.com/en-us/data-center/",
    summary: "Integrated AI hardware systems and networking for data centers.",
    whyItMatters:
      "This is where NVIDIA monetizes whole-system demand instead of just selling components.",
    replacementSketch: [
      "Open cloud orchestration and marketplace layers can soften pricing power even when the hardware remains scarce.",
      "The nearer AI infrastructure gets to a commodity service, the harder it becomes to sustain premium bundling indefinitely.",
    ],
    alternativeSlugs: ["openstack-cloud", "minio-object-storage"],
    sourceIds: ["nvidia-data-center", "openstack", "minio"],
    technologyWaveIds: ["printed-electronics"],
  },
  {
    slug: "apple-icloud",
    companySlug: "apple",
    name: "iCloud",
    category: "Consumer cloud",
    homepageUrl: "https://www.apple.com/icloud/",
    summary: "Apple's storage, sync, backup, and ecosystem glue service.",
    whyItMatters: "iCloud keeps Apple devices feeling conveniently entangled.",
    replacementSketch: [
      "Self-hosted or peer-to-peer sync tools break the assumption that convenience requires centralized platform rent.",
      "The switching cost falls further if AI assistants can handle migration, backups, and device setup chores.",
    ],
    alternativeSlugs: ["nextcloud-platform", "syncthing-network"],
    sourceIds: ["apple-services", "nextcloud", "syncthing"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "apple-app-store",
    companySlug: "apple",
    name: "App Store",
    category: "Distribution platform",
    homepageUrl: "https://www.apple.com/app-store/",
    summary: "Apple's tightly controlled marketplace for software distribution on iOS.",
    whyItMatters: "The App Store monetizes trust, defaults, and gatekeeping all at once.",
    replacementSketch: [
      "Alternative distribution and web-native applications reduce the leverage of a single gatekeeper.",
      "Bitcoin-native payments and portable identities can weaken the need for bundled app-store toll booths.",
    ],
    alternativeSlugs: ["f-droid", "web-app-stack"],
    sourceIds: ["apple-services", "grapheneos"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "microsoft-365-suite",
    companySlug: "microsoft",
    name: "Microsoft 365",
    category: "Productivity software",
    homepageUrl: "https://www.microsoft.com/en-us/microsoft-365",
    summary: "Subscription bundle for documents, collaboration, email, and enterprise workflows.",
    whyItMatters: "This is one of Microsoft's most obvious rent-capture surfaces.",
    replacementSketch: [
      "Open office suites plus self-hosted collaboration are already good enough for more organizations than current procurement habits admit.",
      "AI-mediated file conversion and workflow migration should keep lowering switching pain.",
    ],
    alternativeSlugs: ["libreoffice-suite", "nextcloud-collaboration"],
    sourceIds: ["microsoft-365", "libreoffice", "nextcloud"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "microsoft-github",
    companySlug: "microsoft",
    name: "GitHub",
    category: "Developer platform",
    homepageUrl: "https://github.com/",
    summary: "Code hosting, collaboration, and developer workflow platform.",
    whyItMatters:
      "GitHub's value comes from network effects in open-source and enterprise development workflows.",
    replacementSketch: [
      "Open Git hosting and decentralized forge concepts reduce dependence on a single social layer for software development.",
      "AI-assisted migration can make self-hosting or federation much less operationally annoying.",
    ],
    alternativeSlugs: ["gitea-forge", "self-hosted-git"],
    sourceIds: ["microsoft-investor", "gitea"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "google-search",
    companySlug: "alphabet",
    name: "Google Search",
    category: "Search engine",
    homepageUrl: "https://www.google.com/",
    summary: "Alphabet's flagship query and ad-distribution surface.",
    whyItMatters: "Search still funds a startling amount of Google's empire.",
    replacementSketch: [
      "Open metasearch and smaller search providers can disaggregate parts of the search experience.",
      "Agentic AI may move value from traditional ranked pages toward multi-source synthesis layers.",
    ],
    alternativeSlugs: ["searxng-search", "yacy-search"],
    sourceIds: ["google-products", "searxng"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "youtube",
    companySlug: "alphabet",
    name: "YouTube",
    category: "Video platform",
    homepageUrl: "https://www.youtube.com/",
    summary: "Massive hosted video and creator platform with ad and subscription monetization.",
    whyItMatters: "YouTube combines distribution, monetization, and default discoverability.",
    replacementSketch: [
      "Federated video and direct payment rails can reduce the need for a single platform to intermediate every creator-audience relationship.",
      "AI-assisted subtitling, moderation, and discovery lower some of the operational excuses for centralization.",
    ],
    alternativeSlugs: ["peertube-video", "nostr-video"],
    sourceIds: ["google-products", "peertube"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "aws-platform",
    companySlug: "amazon",
    name: "AWS",
    category: "Cloud platform",
    homepageUrl: "https://aws.amazon.com/",
    summary: "Cloud infrastructure and managed services platform.",
    whyItMatters:
      "AWS is one of the clearest examples of software abstraction becoming a giant toll road.",
    replacementSketch: [
      "Open infrastructure plus better automation can move more workloads off hyperscaler lock-in.",
      "Decentralized compute markets make sense first at the edges, in bursts, and for workloads that tolerate heterogeneity.",
    ],
    alternativeSlugs: ["openstack-cloud", "akash-network", "minio-object-storage"],
    sourceIds: ["aws", "openstack", "akash", "minio"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "amazon-marketplace",
    companySlug: "amazon",
    name: "Amazon Marketplace",
    category: "Commerce platform",
    homepageUrl: "https://www.amazon.com/",
    summary: "Merchant marketplace with integrated logistics and demand capture.",
    whyItMatters: "The marketplace lets Amazon mediate both buyer attention and seller dependence.",
    replacementSketch: [
      "Open commerce stacks let brands own their relationship with customers instead of renting it.",
      "Microfactories and regional logistics can reduce how much of the value chain needs a centralized marketplace at all.",
    ],
    alternativeSlugs: ["open-food-network-marketplace", "saleor-commerce"],
    sourceIds: ["amazon-store", "open-food-network"],
    technologyWaveIds: ["microfactories", "additive-manufacturing"],
  },
  {
    slug: "instagram",
    companySlug: "meta-platforms",
    name: "Instagram",
    category: "Social platform",
    homepageUrl: "https://www.instagram.com/",
    summary: "Photo and short-form social platform with immense creator and advertiser gravity.",
    whyItMatters: "Instagram monetizes cultural attention at scale.",
    replacementSketch: [
      "Federated social graphs can weaken the assumption that creators must rent distribution from a single feed algorithm.",
      "Portable identities and payment rails make creator businesses less platform-dependent over time.",
    ],
    alternativeSlugs: ["pixelfed-social", "mastodon-social"],
    sourceIds: ["meta-tech", "pixelfed", "mastodon"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "whatsapp-platform",
    companySlug: "meta-platforms",
    name: "WhatsApp",
    category: "Messaging",
    homepageUrl: "https://www.whatsapp.com/",
    summary: "Global messaging network with powerful cross-border reach.",
    whyItMatters: "WhatsApp is one of the planet's default private communication layers.",
    replacementSketch: [
      "Open messaging protocols and encrypted self-hosted tooling make proprietary messaging less inevitable.",
      "Micropayments and protocol-native spam resistance could create healthier open messaging economics.",
    ],
    alternativeSlugs: ["matrix-messaging", "signal-messaging"],
    sourceIds: ["whatsapp", "matrix"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "vmware-vsphere",
    companySlug: "broadcom",
    name: "VMware virtualization stack",
    category: "Enterprise infrastructure software",
    homepageUrl: "https://www.broadcom.com/products/software/vmware",
    summary: "Virtualization and private cloud control plane software.",
    whyItMatters: "This is one of Broadcom's most obviously replaceable rent-heavy layers.",
    replacementSketch: [
      "Open virtualization stacks already exist and are increasingly production-worthy.",
      "Incumbent pricing pressure often does half the adoption work for the alternatives.",
    ],
    alternativeSlugs: ["proxmox-ve", "openstack-cloud"],
    sourceIds: ["vmware", "proxmox", "openstack"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "broadcom-networking",
    companySlug: "broadcom",
    name: "Broadcom networking silicon",
    category: "Semiconductor infrastructure",
    homepageUrl: "https://www.broadcom.com/",
    summary: "Critical chips and connectivity layers for data-center and telecom infrastructure.",
    whyItMatters:
      "This is the part of Broadcom that remains stubbornly physical, capital-intensive, and supply-chain bound.",
    replacementSketch: [
      "Open networking software matters, but replacing the silicon layer itself is much slower and more capital-intensive.",
      "Localized electronics tooling may erode some hardware rents over time, but not overnight and not at frontier scale.",
    ],
    alternativeSlugs: ["open-networking-stack"],
    sourceIds: ["broadcom-home", "broadcom-investor"],
    technologyWaveIds: ["printed-electronics"],
  },
  {
    slug: "tesla-supercharger",
    companySlug: "tesla",
    name: "Supercharger network",
    category: "Charging infrastructure",
    homepageUrl: "https://www.tesla.com/supercharger",
    summary: "Tesla's branded fast-charging network and related ecosystem control surface.",
    whyItMatters: "Charging infrastructure deepens customer lock-in and brand trust.",
    replacementSketch: [
      "Open charging standards and independently operated networks can erode brand-tied infrastructure advantage.",
      "Localized energy production makes charging less dependent on a vertically integrated stack.",
    ],
    alternativeSlugs: ["openevse-charging", "ocpp-ecosystem"],
    sourceIds: ["tesla-energy", "openevse"],
    technologyWaveIds: ["distributed-energy"],
  },
  {
    slug: "tesla-energy-stack",
    companySlug: "tesla",
    name: "Powerwall and Megapack",
    category: "Distributed energy",
    homepageUrl: "https://www.tesla.com/energy",
    summary: "Energy storage products and software for homes and grids.",
    whyItMatters:
      "This is where Tesla's software and hardware story merges with the broader energy transition.",
    replacementSketch: [
      "Open energy management layers can reduce how much value one vendor captures from the full stack.",
      "Printable solar, better local storage economics, and microgrid tooling could make the category much more modular.",
    ],
    alternativeSlugs: ["openems-energy", "home-assistant-energy"],
    sourceIds: ["tesla-energy", "openems"],
    technologyWaveIds: ["distributed-energy"],
  },
  {
    slug: "geico-insurance",
    companySlug: "berkshire-hathaway",
    name: "GEICO insurance",
    category: "Insurance",
    homepageUrl: "https://www.geico.com/",
    summary: "Consumer auto insurance under Berkshire's umbrella.",
    whyItMatters: "Insurance is a major Berkshire cash engine and an unusually regulated moat.",
    replacementSketch: [
      "Community and mutual insurance models can pressure certain niches even if they do not replace national carriers outright.",
      "Open actuarial and underwriting tooling matters more for transparency than for immediate full disruption.",
    ],
    alternativeSlugs: ["mutual-insurance-models"],
    sourceIds: ["geico", "berkshire-reports"],
    technologyWaveIds: ["bitcoin-native-coordination"],
  },
  {
    slug: "berkshire-energy",
    companySlug: "berkshire-hathaway",
    name: "Berkshire Hathaway Energy",
    category: "Utilities",
    homepageUrl: "https://www.berkshirehathaway.com/",
    summary: "Utility and energy infrastructure operations within Berkshire.",
    whyItMatters: "Utilities are one of Berkshire's most durable real-world moats.",
    replacementSketch: [
      "Distributed energy and local microgrids can reduce dependence on centralized utility structures at the margins.",
      "Open control layers matter even when the physical grid remains regulated and centralized.",
    ],
    alternativeSlugs: ["openems-energy", "community-microgrids"],
    sourceIds: ["berkshire-reports", "openems"],
    technologyWaveIds: ["distributed-energy"],
  },
  {
    slug: "walmart-marketplace",
    companySlug: "walmart",
    name: "Walmart Marketplace",
    category: "Commerce platform",
    homepageUrl: "https://www.walmart.com/",
    summary: "Third-party marketplace layer attached to Walmart's retail ecosystem.",
    whyItMatters:
      "Marketplace control lets Walmart extend its sourcing and distribution advantage into platform economics.",
    replacementSketch: [
      "Open marketplace tooling and cooperative commerce weaken the need for giant centralized intermediaries in many verticals.",
      "Microfactories and local fulfillment can shift more commerce toward regional networks.",
    ],
    alternativeSlugs: ["open-food-network-marketplace", "saleor-commerce"],
    sourceIds: ["walmart-store", "open-food-network"],
    technologyWaveIds: ["microfactories", "additive-manufacturing"],
  },
  {
    slug: "walmart-grocery",
    companySlug: "walmart",
    name: "Walmart Grocery",
    category: "Retail operations",
    homepageUrl: "https://www.walmart.com/cp/grocery/976759",
    summary: "Mass-scale grocery and daily essentials distribution.",
    whyItMatters:
      "Grocery is where Walmart's physical coordination capabilities are especially hard to imitate.",
    replacementSketch: [
      "Producer-owned marketplaces and local distribution networks can create more resilient alternatives in specific communities.",
      "Open supply coordination software matters more if localized production keeps improving.",
    ],
    alternativeSlugs: ["open-food-network-marketplace", "community-grocery-coops"],
    sourceIds: ["walmart-store", "walmart-about", "open-food-network"],
    technologyWaveIds: ["microfactories", "additive-manufacturing"],
  },
];

export const products: Product[] = rawProducts.map((product) => ({
  ...product,
  disruptionConceptSlugs: [],
  maybeDisruptionException: null,
}));

export const alternatives: Alternative[] = [
  {
    slug: "rocm",
    productSlug: "nvidia-cuda",
    name: "ROCm",
    kind: "open-source",
    homepageUrl: "https://rocm.docs.amd.com/",
    summary:
      "AMD's open compute stack and the clearest current pressure valve on CUDA exclusivity.",
    metrics: {
      openness: metric(
        8.8,
        "More open and portable than CUDA-centric workflows.",
        ["amd-rocm"],
        "high",
      ),
      decentralizationFit: metric(
        6.5,
        "Helps workloads migrate off one vendor's stack, but still depends on major hardware suppliers.",
        ["amd-rocm"],
        "medium",
      ),
      readiness: metric(
        6.8,
        "Viable in serious environments, though still behind CUDA's ecosystem depth.",
        ["amd-rocm"],
        "medium",
      ),
      costLeverage: metric(
        7.1,
        "Its main value is forcing incumbent pricing and portability conversations.",
        ["amd-rocm"],
        "medium",
      ),
    },
    sourceIds: ["amd-rocm"],
  },
  {
    slug: "akash-network",
    productSlug: "nvidia-cuda",
    name: "Akash Network",
    kind: "decentralized",
    homepageUrl: "https://akash.network/",
    summary:
      "Marketplace for distributed compute capacity, useful as a thesis proof for open GPU markets.",
    metrics: {
      openness: metric(
        7.6,
        "Protocol-driven market model is far more open than bundled proprietary capacity.",
        ["akash"],
        "medium",
      ),
      decentralizationFit: metric(
        9.0,
        "Distributed capacity brokering is the core idea.",
        ["akash"],
        "high",
      ),
      readiness: metric(
        5.2,
        "Promising but not yet a comprehensive substitute for hyperscaler reliability.",
        ["akash"],
        "medium",
      ),
      costLeverage: metric(
        6.8,
        "Useful for pricing pressure and burst capacity, less so for universal replacement.",
        ["akash"],
        "medium",
      ),
    },
    sourceIds: ["akash"],
  },
  {
    slug: "openstack-cloud",
    productSlug: "nvidia-dgx",
    name: "OpenStack",
    kind: "open-source",
    homepageUrl: "https://www.openstack.org/",
    summary: "Open cloud control plane used in private and public deployments.",
    metrics: {
      openness: metric(8.7, "Open governance and open deployment model.", ["openstack"], "high"),
      decentralizationFit: metric(
        7.1,
        "Makes private or distributed cloud deployment more plausible.",
        ["openstack"],
        "medium",
      ),
      readiness: metric(
        7.3,
        "Mature in capable hands, though operationally heavier than managed hyperscaler options.",
        ["openstack"],
        "high",
      ),
      costLeverage: metric(
        7.4,
        "Creates meaningful pricing pressure on managed cloud stacks.",
        ["openstack"],
        "medium",
      ),
    },
    sourceIds: ["openstack"],
  },
  {
    slug: "minio-object-storage",
    productSlug: "nvidia-dgx",
    name: "MinIO",
    kind: "open-source",
    homepageUrl: "https://min.io/",
    summary:
      "High-performance object storage alternative relevant to AI and cloud infrastructure stacks.",
    metrics: {
      openness: metric(
        8.1,
        "Strong user control and flexible deployment surface.",
        ["minio"],
        "medium",
      ),
      decentralizationFit: metric(
        6.8,
        "Helps unbundle storage from hyperscaler lock-in.",
        ["minio"],
        "medium",
      ),
      readiness: metric(8.0, "Widely used and operationally credible.", ["minio"], "high"),
      costLeverage: metric(
        7.2,
        "Useful for reducing dependency on managed storage pricing.",
        ["minio"],
        "medium",
      ),
    },
    sourceIds: ["minio"],
  },
  {
    slug: "nextcloud-platform",
    productSlug: "apple-icloud",
    name: "Nextcloud",
    kind: "open-source",
    homepageUrl: "https://nextcloud.com/",
    summary: "Self-hosted sync, file, and collaboration platform.",
    metrics: {
      openness: metric(
        9.2,
        "Users retain far more control over their storage and deployment model.",
        ["nextcloud"],
        "high",
      ),
      decentralizationFit: metric(
        8.5,
        "Self-hosting and federation are native fits.",
        ["nextcloud"],
        "high",
      ),
      readiness: metric(
        8.1,
        "Mature enough for real teams and households willing to operate it.",
        ["nextcloud"],
        "high",
      ),
      costLeverage: metric(
        8.3,
        "Meaningfully compresses the idea that premium sync must come from a device vendor.",
        ["nextcloud"],
        "medium",
      ),
    },
    sourceIds: ["nextcloud"],
  },
  {
    slug: "syncthing-network",
    productSlug: "apple-icloud",
    name: "Syncthing",
    kind: "open-source",
    homepageUrl: "https://syncthing.net/",
    summary: "Peer-to-peer file synchronization without a mandatory central landlord.",
    metrics: {
      openness: metric(9.5, "Exceptionally user-controlled and open.", ["syncthing"], "high"),
      decentralizationFit: metric(
        9.3,
        "Peer-to-peer sync is decentralization in literal form.",
        ["syncthing"],
        "high",
      ),
      readiness: metric(
        7.4,
        "Excellent for many use cases, though less polished than mainstream consumer cloud products.",
        ["syncthing"],
        "medium",
      ),
      costLeverage: metric(
        8.0,
        "Strong pressure on the idea that sync itself deserves premium platform rent.",
        ["syncthing"],
        "medium",
      ),
    },
    sourceIds: ["syncthing"],
  },
  {
    slug: "f-droid",
    productSlug: "apple-app-store",
    name: "F-Droid",
    kind: "open-source",
    homepageUrl: "https://f-droid.org/",
    summary: "Open catalog and distribution model for Android applications.",
    metrics: {
      openness: metric(9.6, "Open app distribution is the point.", ["grapheneos"], "high"),
      decentralizationFit: metric(
        8.2,
        "Alternative distribution reduces single-gatekeeper control.",
        ["grapheneos"],
        "medium",
      ),
      readiness: metric(
        6.5,
        "Useful today, though still well outside the mainstream iPhone comfort zone.",
        ["grapheneos"],
        "medium",
      ),
      costLeverage: metric(
        7.7,
        "Shows the app-store tax is a policy choice rather than a law of physics.",
        ["grapheneos"],
        "medium",
      ),
    },
    sourceIds: ["grapheneos"],
  },
  {
    slug: "web-app-stack",
    productSlug: "apple-app-store",
    name: "Progressive web apps",
    kind: "protocol",
    homepageUrl: "https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps",
    summary: "Open web distribution model that bypasses some app-store friction.",
    metrics: {
      openness: metric(
        9.0,
        "The open web remains the least rent-seeking app store on offer.",
        ["grapheneos"],
        "medium",
      ),
      decentralizationFit: metric(
        8.1,
        "Standards-based distribution weakens centralized approval bottlenecks.",
        ["grapheneos"],
        "medium",
      ),
      readiness: metric(
        7.2,
        "Good enough for many use cases, still constrained by platform policies for others.",
        ["grapheneos"],
        "medium",
      ),
      costLeverage: metric(
        8.4,
        "Every viable web app is one less reason to accept mandatory store tolls.",
        ["grapheneos"],
        "medium",
      ),
    },
    sourceIds: ["grapheneos"],
  },
  {
    slug: "libreoffice-suite",
    productSlug: "microsoft-365-suite",
    name: "LibreOffice",
    kind: "open-source",
    homepageUrl: "https://www.libreoffice.org/",
    summary: "Open desktop productivity suite for documents, spreadsheets, and presentations.",
    metrics: {
      openness: metric(
        9.6,
        "Excellent user control and open formats orientation.",
        ["libreoffice"],
        "high",
      ),
      decentralizationFit: metric(
        8.4,
        "Local-first productivity reduces dependence on subscription landlords.",
        ["libreoffice"],
        "high",
      ),
      readiness: metric(
        8.0,
        "Highly usable today, especially where exact Microsoft workflow fidelity is not mandatory.",
        ["libreoffice"],
        "high",
      ),
      costLeverage: metric(
        8.7,
        "One of the clearest examples of a mature free alternative compressing incumbents.",
        ["libreoffice"],
        "high",
      ),
    },
    sourceIds: ["libreoffice"],
  },
  {
    slug: "nextcloud-collaboration",
    productSlug: "microsoft-365-suite",
    name: "Nextcloud + Collabora/ONLYOFFICE",
    kind: "hybrid",
    homepageUrl: "https://nextcloud.com/",
    summary: "Self-hosted collaboration stack for storage, docs, and workflows.",
    metrics: {
      openness: metric(
        8.9,
        "Far more controllable than a closed SaaS productivity suite.",
        ["nextcloud"],
        "high",
      ),
      decentralizationFit: metric(
        8.7,
        "Can be run by the organization itself rather than a distant platform.",
        ["nextcloud"],
        "high",
      ),
      readiness: metric(
        7.5,
        "Quite usable, though adoption depends on operational tolerance and workflow needs.",
        ["nextcloud"],
        "medium",
      ),
      costLeverage: metric(
        8.2,
        "Creates real negotiating leverage against per-seat software rent.",
        ["nextcloud"],
        "medium",
      ),
    },
    sourceIds: ["nextcloud"],
  },
  {
    slug: "gitea-forge",
    productSlug: "microsoft-github",
    name: "Gitea",
    kind: "open-source",
    homepageUrl: "https://about.gitea.com/",
    summary: "Lightweight open forge for code hosting and collaboration.",
    metrics: {
      openness: metric(9.4, "Open and self-hostable by design.", ["gitea"], "high"),
      decentralizationFit: metric(
        8.8,
        "Fits federated or self-hosted development workflows naturally.",
        ["gitea"],
        "high",
      ),
      readiness: metric(
        8.0,
        "Mature enough for many internal and community use cases.",
        ["gitea"],
        "high",
      ),
      costLeverage: metric(
        8.1,
        "A direct reminder that code hosting does not have to be socially monopolized.",
        ["gitea"],
        "medium",
      ),
    },
    sourceIds: ["gitea"],
  },
  {
    slug: "self-hosted-git",
    productSlug: "microsoft-github",
    name: "Self-hosted Git platforms",
    kind: "hybrid",
    homepageUrl: "https://about.gitea.com/",
    summary: "Umbrella category for self-hosted Git services such as Gitea and GitLab CE.",
    metrics: {
      openness: metric(
        8.9,
        "Organizations can own the forge instead of borrowing it.",
        ["gitea"],
        "medium",
      ),
      decentralizationFit: metric(
        8.0,
        "Moves developer coordination away from a single public platform.",
        ["gitea"],
        "medium",
      ),
      readiness: metric(
        8.1,
        "Operationally straightforward for many engineering teams.",
        ["gitea"],
        "medium",
      ),
      costLeverage: metric(
        7.9,
        "Useful where compliance or cost concerns justify the move.",
        ["gitea"],
        "medium",
      ),
    },
    sourceIds: ["gitea"],
  },
  {
    slug: "searxng-search",
    productSlug: "google-search",
    name: "SearXNG",
    kind: "open-source",
    homepageUrl: "https://github.com/searxng/searxng",
    repoUrl: "https://github.com/searxng/searxng",
    summary:
      "Open metasearch engine that lets operators own their search interface and aggregation logic.",
    metrics: {
      openness: metric(9.7, "Highly open and operator-controlled.", ["searxng"], "high"),
      decentralizationFit: metric(8.5, "Any operator can run an instance.", ["searxng"], "high"),
      readiness: metric(
        6.6,
        "Useful now, though still not a drop-in replacement for Google's scale or data advantage.",
        ["searxng"],
        "medium",
      ),
      costLeverage: metric(
        6.9,
        "Strong as a proof that search need not be singularly centralized.",
        ["searxng"],
        "medium",
      ),
    },
    sourceIds: ["searxng"],
  },
  {
    slug: "yacy-search",
    productSlug: "google-search",
    name: "YaCy",
    kind: "decentralized",
    homepageUrl: "https://yacy.net/",
    summary: "Peer-to-peer search engine project.",
    metrics: {
      openness: metric(9.3, "Strongly aligned with open search principles.", ["searxng"], "medium"),
      decentralizationFit: metric(
        9.2,
        "Distributed search is the explicit design goal.",
        ["searxng"],
        "medium",
      ),
      readiness: metric(
        4.9,
        "Interesting but not mainstream or polished enough for general replacement.",
        ["searxng"],
        "speculative",
      ),
      costLeverage: metric(
        5.2,
        "More important as directional evidence than immediate competitive pressure.",
        ["searxng"],
        "speculative",
      ),
    },
    sourceIds: ["searxng"],
  },
  {
    slug: "peertube-video",
    productSlug: "youtube",
    name: "PeerTube",
    kind: "decentralized",
    homepageUrl: "https://joinpeertube.org/",
    summary: "Federated video hosting platform.",
    metrics: {
      openness: metric(9.4, "Open-source and federation-friendly by design.", ["peertube"], "high"),
      decentralizationFit: metric(
        9.1,
        "Directly attacks the assumption that video must live on one giant platform.",
        ["peertube"],
        "high",
      ),
      readiness: metric(
        6.3,
        "Strong for communities, not yet equal to YouTube's convenience or reach.",
        ["peertube"],
        "medium",
      ),
      costLeverage: metric(
        6.7,
        "Useful pressure where creator communities can move with their audience.",
        ["peertube"],
        "medium",
      ),
    },
    sourceIds: ["peertube"],
  },
  {
    slug: "nostr-video",
    productSlug: "youtube",
    name: "Nostr video clients",
    kind: "protocol",
    homepageUrl: "https://nostr.com/",
    summary:
      "Protocol-native publishing tools with Bitcoin-adjacent identity and monetization possibilities.",
    metrics: {
      openness: metric(
        8.8,
        "Protocol-centric and resistant to single-platform control.",
        ["matrix"],
        "speculative",
      ),
      decentralizationFit: metric(
        9.0,
        "The core premise is distributed publishing and identity.",
        ["matrix"],
        "speculative",
      ),
      readiness: metric(
        4.8,
        "Early and fragmented compared with mainstream creator platforms.",
        ["matrix"],
        "speculative",
      ),
      costLeverage: metric(
        5.9,
        "Strategically important even if still early.",
        ["matrix"],
        "speculative",
      ),
    },
    sourceIds: ["matrix"],
  },
  {
    slug: "pixelfed-social",
    productSlug: "instagram",
    name: "Pixelfed",
    kind: "open-source",
    homepageUrl: "https://pixelfed.org/",
    summary: "Federated photo-sharing network built on ActivityPub.",
    metrics: {
      openness: metric(9.4, "Strong open-source and federation posture.", ["pixelfed"], "high"),
      decentralizationFit: metric(
        9.1,
        "Makes social photo-sharing less dependent on one company.",
        ["pixelfed"],
        "high",
      ),
      readiness: metric(
        6.2,
        "Compelling for communities, still behind Instagram in mainstream creator gravity.",
        ["pixelfed"],
        "medium",
      ),
      costLeverage: metric(
        6.8,
        "Provides credible pressure on a platform that behaves like it invented photographs.",
        ["pixelfed"],
        "medium",
      ),
    },
    sourceIds: ["pixelfed"],
  },
  {
    slug: "mastodon-social",
    productSlug: "instagram",
    name: "Mastodon",
    kind: "open-source",
    homepageUrl: "https://joinmastodon.org/",
    summary:
      "Federated social network and a visible proof that large-scale social publishing can use open protocols.",
    metrics: {
      openness: metric(9.5, "Open-source and protocol-friendly.", ["mastodon"], "high"),
      decentralizationFit: metric(
        9.3,
        "Federation is core to the product model.",
        ["mastodon"],
        "high",
      ),
      readiness: metric(
        6.9,
        "Already viable for many users, though social graph migration remains a hurdle.",
        ["mastodon"],
        "medium",
      ),
      costLeverage: metric(
        7.0,
        "Pressures centralized platforms by proving another model is possible.",
        ["mastodon"],
        "medium",
      ),
    },
    sourceIds: ["mastodon"],
  },
  {
    slug: "matrix-messaging",
    productSlug: "whatsapp-platform",
    name: "Matrix",
    kind: "protocol",
    homepageUrl: "https://matrix.org/",
    summary: "Open messaging protocol with self-hosting and federation.",
    metrics: {
      openness: metric(
        9.5,
        "One of the clearest open alternatives to proprietary messaging silos.",
        ["matrix"],
        "high",
      ),
      decentralizationFit: metric(
        9.4,
        "Federation and user-controlled hosting are the central proposition.",
        ["matrix"],
        "high",
      ),
      readiness: metric(
        7.2,
        "Mature enough for serious communities and organizations.",
        ["matrix"],
        "medium",
      ),
      costLeverage: metric(
        7.1,
        "Useful pressure on the assumption that messaging defaults should be platform-owned.",
        ["matrix"],
        "medium",
      ),
    },
    sourceIds: ["matrix"],
  },
  {
    slug: "signal-messaging",
    productSlug: "whatsapp-platform",
    name: "Signal",
    kind: "hybrid",
    homepageUrl: "https://signal.org/",
    summary:
      "Privacy-focused messaging service that remains more centralized than Matrix but still pushes the market toward better norms.",
    metrics: {
      openness: metric(
        8.3,
        "Strong protocol and software openness, though not fully decentralized.",
        ["matrix"],
        "medium",
      ),
      decentralizationFit: metric(
        5.3,
        "Much better on privacy than on federation.",
        ["matrix"],
        "medium",
      ),
      readiness: metric(8.8, "Highly usable today.", ["matrix"], "high"),
      costLeverage: metric(
        7.4,
        "Important because it proves mainstream messaging quality need not require ad-driven ownership models.",
        ["matrix"],
        "medium",
      ),
    },
    sourceIds: ["matrix"],
  },
  {
    slug: "proxmox-ve",
    productSlug: "vmware-vsphere",
    name: "Proxmox VE",
    kind: "open-source",
    homepageUrl: "https://www.proxmox.com/en/proxmox-virtual-environment",
    summary: "Open-source virtualization stack with increasing enterprise appeal.",
    metrics: {
      openness: metric(9.1, "Open and operator-controlled.", ["proxmox"], "high"),
      decentralizationFit: metric(
        8.0,
        "Makes self-operated infrastructure more attractive.",
        ["proxmox"],
        "medium",
      ),
      readiness: metric(
        8.3,
        "Now credible for a wide range of production workloads.",
        ["proxmox"],
        "high",
      ),
      costLeverage: metric(
        8.7,
        "Directly compresses premium VMware pricing logic.",
        ["proxmox"],
        "high",
      ),
    },
    sourceIds: ["proxmox"],
  },
  {
    slug: "open-networking-stack",
    productSlug: "broadcom-networking",
    name: "Open networking software stacks",
    kind: "hybrid",
    homepageUrl: "https://opennetlinux.org/",
    summary:
      "Open switching and control plane efforts that erode some software-side networking lock-in.",
    metrics: {
      openness: metric(
        8.2,
        "Moves some value away from closed control surfaces.",
        ["broadcom-home"],
        "medium",
      ),
      decentralizationFit: metric(
        5.6,
        "Helpful, but the silicon supply chain remains stubbornly concentrated.",
        ["broadcom-home"],
        "medium",
      ),
      readiness: metric(
        6.1,
        "Useful in pockets, still far from replacing the entire incumbent stack.",
        ["broadcom-home"],
        "medium",
      ),
      costLeverage: metric(
        5.9,
        "Reduces some premium capture without overturning the hardware layer.",
        ["broadcom-home"],
        "medium",
      ),
    },
    sourceIds: ["broadcom-home"],
  },
  {
    slug: "openevse-charging",
    productSlug: "tesla-supercharger",
    name: "OpenEVSE",
    kind: "open-source",
    homepageUrl: "https://openevse.com/",
    summary: "Open EV charging hardware and control stack.",
    metrics: {
      openness: metric(
        9.0,
        "A genuinely open answer to proprietary charging stacks.",
        ["openevse"],
        "high",
      ),
      decentralizationFit: metric(
        8.7,
        "Charging can be deployed locally without a single network landlord.",
        ["openevse"],
        "high",
      ),
      readiness: metric(
        7.4,
        "Strong for DIY and semi-professional deployments, less turnkey than Tesla's network.",
        ["openevse"],
        "medium",
      ),
      costLeverage: metric(
        7.6,
        "Useful where openness matters more than brand convenience.",
        ["openevse"],
        "medium",
      ),
    },
    sourceIds: ["openevse"],
  },
  {
    slug: "ocpp-ecosystem",
    productSlug: "tesla-supercharger",
    name: "OCPP-based charging ecosystem",
    kind: "protocol",
    homepageUrl: "https://openchargealliance.org/protocols/ocpp-protocols/",
    summary: "Open Charge Point Protocol ecosystem for interoperable EV charging infrastructure.",
    metrics: {
      openness: metric(8.4, "Open protocol lowers proprietary lock-in.", ["openevse"], "medium"),
      decentralizationFit: metric(
        8.0,
        "Interoperability allows more operators to participate.",
        ["openevse"],
        "medium",
      ),
      readiness: metric(
        8.1,
        "Already meaningful in real charging deployments.",
        ["openevse"],
        "medium",
      ),
      costLeverage: metric(
        7.2,
        "Undercuts the assumption that fast charging must live inside one branded network.",
        ["openevse"],
        "medium",
      ),
    },
    sourceIds: ["openevse"],
  },
  {
    slug: "openems-energy",
    productSlug: "tesla-energy-stack",
    name: "OpenEMS",
    kind: "open-source",
    homepageUrl: "https://openems.io/",
    summary: "Open energy management platform for distributed energy systems.",
    metrics: {
      openness: metric(9.1, "Open control plane for energy orchestration.", ["openems"], "high"),
      decentralizationFit: metric(
        8.9,
        "Designed for distributed energy control.",
        ["openems"],
        "high",
      ),
      readiness: metric(
        7.1,
        "Good technical base, still less consumer-friendly than integrated vendor stacks.",
        ["openems"],
        "medium",
      ),
      costLeverage: metric(
        7.5,
        "Useful as energy hardware becomes more modular and software-defined.",
        ["openems"],
        "medium",
      ),
    },
    sourceIds: ["openems"],
  },
  {
    slug: "home-assistant-energy",
    productSlug: "tesla-energy-stack",
    name: "Home Assistant Energy",
    kind: "open-source",
    homepageUrl: "https://www.home-assistant.io/",
    summary:
      "Open home automation platform with growing energy monitoring and control capabilities.",
    metrics: {
      openness: metric(9.0, "Strong open-source home control model.", ["openems"], "medium"),
      decentralizationFit: metric(
        8.3,
        "Local-first automation fits distributed energy well.",
        ["openems"],
        "medium",
      ),
      readiness: metric(
        8.0,
        "Already widely used by technically comfortable households.",
        ["openems"],
        "medium",
      ),
      costLeverage: metric(
        7.0,
        "Reduces dependence on vertically integrated smart-home energy stacks.",
        ["openems"],
        "medium",
      ),
    },
    sourceIds: ["openems"],
  },
  {
    slug: "mutual-insurance-models",
    productSlug: "geico-insurance",
    name: "Mutual and cooperative insurance models",
    kind: "cooperative",
    summary:
      "Member-aligned insurance structures that reduce shareholder extraction, even if they remain far from plug-and-play software replacement.",
    metrics: {
      openness: metric(
        6.0,
        "Governance can be more user-aligned than corporate insurers.",
        ["geico", "berkshire-reports"],
        "medium",
      ),
      decentralizationFit: metric(
        4.5,
        "Helpful for governance, less so for rapid technical decentralization.",
        ["geico"],
        "medium",
      ),
      readiness: metric(
        5.9,
        "Real in the world, but niche relative to national giants.",
        ["geico"],
        "medium",
      ),
      costLeverage: metric(
        4.7,
        "Creates conceptual pressure more than immediate platform disruption.",
        ["geico"],
        "medium",
      ),
    },
    sourceIds: ["geico", "berkshire-reports"],
  },
  {
    slug: "community-microgrids",
    productSlug: "berkshire-energy",
    name: "Community microgrids",
    kind: "cooperative",
    summary:
      "Localized energy generation and management models that reduce dependence on large centralized utilities for some use cases.",
    metrics: {
      openness: metric(
        7.2,
        "Community ownership and open controls improve alignment.",
        ["openems"],
        "medium",
      ),
      decentralizationFit: metric(
        8.4,
        "The whole point is more local resilience and control.",
        ["openems"],
        "medium",
      ),
      readiness: metric(
        5.8,
        "Technically plausible, operationally uneven, and often constrained by regulation.",
        ["openems"],
        "medium",
      ),
      costLeverage: metric(
        5.5,
        "Meaningful over long arcs, especially as local energy tooling improves.",
        ["openems"],
        "medium",
      ),
    },
    sourceIds: ["openems"],
  },
  {
    slug: "open-food-network-marketplace",
    productSlug: "walmart-marketplace",
    name: "Open Food Network",
    kind: "open-source",
    homepageUrl: "https://www.openfoodnetwork.org/",
    summary: "Open marketplace software for producers, food hubs, and cooperative commerce.",
    metrics: {
      openness: metric(
        9.2,
        "Open and community-oriented by design.",
        ["open-food-network"],
        "high",
      ),
      decentralizationFit: metric(
        8.8,
        "Optimized for distributed local commerce rather than a single mega-platform.",
        ["open-food-network"],
        "high",
      ),
      readiness: metric(
        7.0,
        "Useful today for regional networks, not a direct Walmart-scale clone.",
        ["open-food-network"],
        "medium",
      ),
      costLeverage: metric(
        7.1,
        "Important as a local alternative to centralized marketplace control.",
        ["open-food-network"],
        "medium",
      ),
    },
    sourceIds: ["open-food-network"],
  },
  {
    slug: "saleor-commerce",
    productSlug: "walmart-marketplace",
    name: "Saleor / open commerce stacks",
    kind: "open-source",
    homepageUrl: "https://saleor.io/",
    summary:
      "Representative open commerce tooling for merchant-owned storefronts and marketplaces.",
    metrics: {
      openness: metric(
        8.5,
        "Merchant-controlled commerce stack rather than platform tenancy.",
        ["open-food-network"],
        "medium",
      ),
      decentralizationFit: metric(
        7.4,
        "Helps merchants own their software layer and customer relationships.",
        ["open-food-network"],
        "medium",
      ),
      readiness: metric(
        7.7,
        "Production-credible with the right team.",
        ["open-food-network"],
        "medium",
      ),
      costLeverage: metric(
        7.3,
        "Compresses the assumption that commerce software must be platform-rented.",
        ["open-food-network"],
        "medium",
      ),
    },
    sourceIds: ["open-food-network"],
  },
  {
    slug: "community-grocery-coops",
    productSlug: "walmart-grocery",
    name: "Community grocery cooperatives",
    kind: "cooperative",
    summary:
      "Member-owned grocery and distribution structures that prioritize local resilience over centralized shareholder extraction.",
    metrics: {
      openness: metric(
        6.8,
        "Governance can be dramatically more aligned than big-box retail.",
        ["open-food-network"],
        "medium",
      ),
      decentralizationFit: metric(
        7.9,
        "Local sourcing and ownership are naturally decentralized.",
        ["open-food-network"],
        "medium",
      ),
      readiness: metric(
        5.7,
        "Real but uneven, and not yet a mass substitute for national-scale convenience.",
        ["open-food-network"],
        "medium",
      ),
      costLeverage: metric(
        5.8,
        "Most effective when paired with open logistics software and stronger local production.",
        ["open-food-network"],
        "medium",
      ),
    },
    sourceIds: ["open-food-network"],
  },
];
