import type { SourceCitation } from "~/lib/domain/types";

const accessedOn = "2026-03-14";

export const sources: SourceCitation[] = [
  {
    id: "nvidia-investor",
    title: "NVIDIA Investor Relations",
    url: "https://investor.nvidia.com/",
    kind: "investor-relations",
    publisher: "NVIDIA",
    note: "Useful for business model, segment framing, and management commentary.",
    accessedOn,
  },
  {
    id: "nvidia-data-center",
    title: "NVIDIA Data Center",
    url: "https://www.nvidia.com/en-us/data-center/",
    kind: "product-page",
    publisher: "NVIDIA",
    note: "Confirms the centrality of accelerated compute and networking products.",
    accessedOn,
  },
  {
    id: "nvidia-cuda",
    title: "CUDA Zone",
    url: "https://developer.nvidia.com/cuda-zone",
    kind: "technical-docs",
    publisher: "NVIDIA",
    note: "Evidence for NVIDIA's software ecosystem lock-in.",
    accessedOn,
  },
  {
    id: "nvidia-marketcap",
    title: "NVIDIA Market Cap",
    url: "https://companiesmarketcap.com/nvidia/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "nvidia-ipo-prospectus",
    title: "NVIDIA final IPO prospectus",
    url: "https://www.sec.gov/Archives/edgar/data/1045810/000101287099000192/0001012870-99-000192.txt",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source for NVIDIA's IPO date, offer price, and post-offering share count.",
    accessedOn,
  },
  {
    id: "amd-rocm",
    title: "AMD ROCm documentation",
    url: "https://rocm.docs.amd.com/",
    kind: "technical-docs",
    publisher: "AMD",
    note: "Shows a credible open compute alternative path to CUDA lock-in.",
    accessedOn,
  },
  {
    id: "apple-investor",
    title: "Apple Investor Relations",
    url: "https://investor.apple.com/",
    kind: "investor-relations",
    publisher: "Apple",
    note: "Primary source for Apple's business mix and strategic narrative.",
    accessedOn,
  },
  {
    id: "apple-iphone",
    title: "Apple iPhone",
    url: "https://www.apple.com/iphone/",
    kind: "product-page",
    publisher: "Apple",
    note: "Flagship hardware and ecosystem entry point.",
    accessedOn,
  },
  {
    id: "apple-services",
    title: "Apple Services",
    url: "https://www.apple.com/services/",
    kind: "product-page",
    publisher: "Apple",
    note: "Evidence for recurring services lock-in around devices.",
    accessedOn,
  },
  {
    id: "apple-marketcap",
    title: "Apple Market Cap",
    url: "https://companiesmarketcap.com/apple/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "apple-ipo-prospectus",
    title: "Apple Computer final IPO prospectus",
    url: "https://www.sec.gov/Archives/edgar/foiadocs/18-02062-FOIA.pdf",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source for Apple's IPO date, offer price, and post-offering share count.",
    accessedOn,
  },
  {
    id: "grapheneos",
    title: "GrapheneOS",
    url: "https://grapheneos.org/",
    kind: "open-source-project",
    publisher: "GrapheneOS",
    note: "Useful counterexample to the idea that mobile stacks must remain fully closed.",
    accessedOn,
  },
  {
    id: "microsoft-investor",
    title: "Microsoft Investor Relations",
    url: "https://www.microsoft.com/en-us/investor",
    kind: "investor-relations",
    publisher: "Microsoft",
    note: "Business structure and strategic priorities.",
    accessedOn,
  },
  {
    id: "microsoft-365",
    title: "Microsoft 365",
    url: "https://www.microsoft.com/en-us/microsoft-365",
    kind: "product-page",
    publisher: "Microsoft",
    note: "Primary productivity subscription reference.",
    accessedOn,
  },
  {
    id: "azure",
    title: "Microsoft Azure",
    url: "https://azure.microsoft.com/",
    kind: "product-page",
    publisher: "Microsoft",
    note: "Cloud infrastructure reference.",
    accessedOn,
  },
  {
    id: "microsoft-marketcap",
    title: "Microsoft Market Cap",
    url: "https://companiesmarketcap.com/microsoft/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "microsoft-ipo-prospectus",
    title: "Microsoft final IPO prospectus",
    url: "https://www.begintoinvest.com/wp-content/uploads/2018/03/Microsoft_prospectus.pdf",
    kind: "regulatory-filing",
    publisher: "Microsoft prospectus archive",
    note: "Prospectus scan used for Microsoft's IPO date, offer price, and post-offering share count.",
    accessedOn,
  },
  {
    id: "libreoffice",
    title: "LibreOffice",
    url: "https://www.libreoffice.org/",
    kind: "open-source-project",
    publisher: "The Document Foundation",
    note: "A durable open-source anchor for productivity-suite alternatives.",
    accessedOn,
  },
  {
    id: "alphabet-investor",
    title: "Alphabet Investor Relations",
    url: "https://abc.xyz/investor/",
    kind: "investor-relations",
    publisher: "Alphabet",
    note: "Primary source for business segments and financial framing.",
    accessedOn,
  },
  {
    id: "google-products",
    title: "Google Products",
    url: "https://about.google/products/",
    kind: "product-page",
    publisher: "Google",
    note: "Broad overview of consumer-facing product footprint.",
    accessedOn,
  },
  {
    id: "google-cloud",
    title: "Google Cloud",
    url: "https://cloud.google.com/",
    kind: "product-page",
    publisher: "Google",
    note: "Cloud and workspace surface area.",
    accessedOn,
  },
  {
    id: "alphabet-marketcap",
    title: "Alphabet Market Cap",
    url: "https://companiesmarketcap.com/alphabet-google/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "alphabet-ipo-prospectus",
    title: "Google final IPO prospectus",
    url: "https://www.sec.gov/Archives/edgar/data/1288776/000119312504143377/d424b4.htm",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source for Google's IPO date, auction clearing price, and post-offering share count.",
    accessedOn,
  },
  {
    id: "searxng",
    title: "SearXNG",
    url: "https://github.com/searxng/searxng",
    kind: "open-source-project",
    publisher: "SearXNG contributors",
    note: "Open metasearch alternative relevant to search decentralization arguments.",
    accessedOn,
  },
  {
    id: "amazon-investor",
    title: "Amazon Investor Relations",
    url: "https://ir.aboutamazon.com/",
    kind: "investor-relations",
    publisher: "Amazon",
    note: "Business mix and management commentary.",
    accessedOn,
  },
  {
    id: "amazon-store",
    title: "Amazon",
    url: "https://www.amazon.com/",
    kind: "product-page",
    publisher: "Amazon",
    note: "Marketplace and retail entry point.",
    accessedOn,
  },
  {
    id: "aws",
    title: "Amazon Web Services",
    url: "https://aws.amazon.com/",
    kind: "product-page",
    publisher: "Amazon",
    note: "Infrastructure and platform services reference.",
    accessedOn,
  },
  {
    id: "amazon-marketcap",
    title: "Amazon Market Cap",
    url: "https://companiesmarketcap.com/amazon/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "amazon-ipo-prospectus",
    title: "Amazon final IPO prospectus",
    url: "https://www.sec.gov/Archives/edgar/data/1018724/000089102097000868/0000891020-97-000868.txt",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source for Amazon's IPO date, offer price, and post-offering share count.",
    accessedOn,
  },
  {
    id: "openstack",
    title: "OpenStack",
    url: "https://www.openstack.org/",
    kind: "open-source-project",
    publisher: "OpenInfra Foundation",
    note: "Canonical open cloud infrastructure reference.",
    accessedOn,
  },
  {
    id: "meta-investor",
    title: "Meta Investor Relations",
    url: "https://investor.atmeta.com/",
    kind: "investor-relations",
    publisher: "Meta",
    note: "Business and financial framing for Meta's platforms.",
    accessedOn,
  },
  {
    id: "meta-tech",
    title: "Meta technologies",
    url: "https://about.meta.com/technologies/",
    kind: "product-page",
    publisher: "Meta",
    note: "Shows the breadth of Meta's consumer products.",
    accessedOn,
  },
  {
    id: "whatsapp",
    title: "WhatsApp",
    url: "https://www.whatsapp.com/",
    kind: "product-page",
    publisher: "Meta",
    note: "Messaging footprint and scale context.",
    accessedOn,
  },
  {
    id: "meta-marketcap",
    title: "Meta Platforms Market Cap",
    url: "https://companiesmarketcap.com/meta-platforms/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "meta-ipo-prospectus",
    title: "Facebook final IPO prospectus",
    url: "https://www.sec.gov/Archives/edgar/data/1326801/000119312512240111/d287954d424b4.htm",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source for Facebook's IPO date and final offer price.",
    accessedOn,
  },
  {
    id: "meta-ipo-registration",
    title: "Facebook Amendment No. 8 to Form S-1",
    url: "https://www.sec.gov/Archives/edgar/data/1326801/000119312512222368/d287954ds1a.htm",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source for Facebook's total Class A and Class B shares outstanding after the IPO.",
    accessedOn,
  },
  {
    id: "mastodon",
    title: "Mastodon",
    url: "https://joinmastodon.org/",
    kind: "open-source-project",
    publisher: "Mastodon",
    note: "Federated social alternative reference.",
    accessedOn,
  },
  {
    id: "broadcom-investor",
    title: "Broadcom Investor Relations",
    url: "https://investors.broadcom.com/",
    kind: "investor-relations",
    publisher: "Broadcom",
    note: "Business mix and acquisition framing.",
    accessedOn,
  },
  {
    id: "vmware",
    title: "Broadcom VMware",
    url: "https://www.broadcom.com/products/software/vmware",
    kind: "product-page",
    publisher: "Broadcom",
    note: "VMware product surface after the acquisition.",
    accessedOn,
  },
  {
    id: "broadcom-home",
    title: "Broadcom",
    url: "https://www.broadcom.com/",
    kind: "product-page",
    publisher: "Broadcom",
    note: "Corporate and product overview.",
    accessedOn,
  },
  {
    id: "broadcom-marketcap",
    title: "Broadcom Market Cap",
    url: "https://companiesmarketcap.com/broadcom/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "broadcom-ipo-prospectus",
    title: "Avago Technologies final IPO prospectus",
    url: "https://www.sec.gov/Archives/edgar/data/1441634/000119312509166258/d424b4.htm",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source for Avago's IPO date, offer price, and post-offering share count before it became Broadcom.",
    accessedOn,
  },
  {
    id: "proxmox",
    title: "Proxmox VE",
    url: "https://www.proxmox.com/en/proxmox-virtual-environment",
    kind: "open-source-project",
    publisher: "Proxmox",
    note: "Prominent open virtualization alternative relevant to VMware replacement.",
    accessedOn,
  },
  {
    id: "tesla-investor",
    title: "Tesla Investor Relations",
    url: "https://ir.tesla.com/",
    kind: "investor-relations",
    publisher: "Tesla",
    note: "Primary source for Tesla's automotive and energy business framing.",
    accessedOn,
  },
  {
    id: "tesla-modely",
    title: "Tesla Model Y",
    url: "https://www.tesla.com/modely",
    kind: "product-page",
    publisher: "Tesla",
    note: "Flagship consumer vehicle reference.",
    accessedOn,
  },
  {
    id: "tesla-energy",
    title: "Tesla Energy",
    url: "https://www.tesla.com/energy",
    kind: "product-page",
    publisher: "Tesla",
    note: "Energy storage and grid product reference.",
    accessedOn,
  },
  {
    id: "tesla-marketcap",
    title: "Tesla Market Cap",
    url: "https://companiesmarketcap.com/tesla/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "tesla-ipo-prospectus",
    title: "Tesla Motors final IPO prospectus",
    url: "https://www.sec.gov/Archives/edgar/data/1318605/000119312510149105/d424b4.htm",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source for Tesla's IPO date, offer price, and post-offering share count.",
    accessedOn,
  },
  {
    id: "openpilot",
    title: "openpilot",
    url: "https://github.com/commaai/openpilot",
    kind: "open-source-project",
    publisher: "comma.ai",
    note: "Open driver-assistance stack relevant to Tesla software claims.",
    accessedOn,
  },
  {
    id: "berkshire-home",
    title: "Berkshire Hathaway",
    url: "https://www.berkshirehathaway.com/",
    kind: "investor-relations",
    publisher: "Berkshire Hathaway",
    note: "Primary corporate overview source.",
    accessedOn,
  },
  {
    id: "berkshire-reports",
    title: "Berkshire Hathaway annual reports",
    url: "https://www.berkshirehathaway.com/reports.html",
    kind: "annual-report",
    publisher: "Berkshire Hathaway",
    note: "Source for conglomerate composition and operating context.",
    accessedOn,
  },
  {
    id: "geico",
    title: "GEICO",
    url: "https://www.geico.com/",
    kind: "product-page",
    publisher: "GEICO",
    note: "Insurance operating business reference.",
    accessedOn,
  },
  {
    id: "bnsf",
    title: "BNSF Railway",
    url: "https://www.bnsf.com/",
    kind: "product-page",
    publisher: "BNSF",
    note: "Rail infrastructure reference.",
    accessedOn,
  },
  {
    id: "berkshire-marketcap",
    title: "Berkshire Hathaway Market Cap",
    url: "https://companiesmarketcap.com/berkshire-hathaway/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "walmart-investor",
    title: "Walmart Investor Relations",
    url: "https://stock.walmart.com/",
    kind: "investor-relations",
    publisher: "Walmart",
    note: "Primary financial and strategic context.",
    accessedOn,
  },
  {
    id: "walmart-store",
    title: "Walmart",
    url: "https://www.walmart.com/",
    kind: "product-page",
    publisher: "Walmart",
    note: "Retail and e-commerce reference.",
    accessedOn,
  },
  {
    id: "walmart-about",
    title: "About Walmart",
    url: "https://corporate.walmart.com/about",
    kind: "analysis",
    publisher: "Walmart",
    note: "Useful overview for scale and operating model.",
    accessedOn,
  },
  {
    id: "walmart-marketcap",
    title: "Walmart Market Cap",
    url: "https://companiesmarketcap.com/walmart/marketcap/",
    kind: "market-data",
    publisher: "CompaniesMarketCap",
    note: "Market cap snapshot reference.",
    accessedOn,
  },
  {
    id: "walmart-stock-split-history",
    title: "Walmart stock split history",
    url: "https://stock.walmart.com/investors/stock-information/stock-split-history/default.aspx",
    kind: "investor-relations",
    publisher: "Walmart",
    note: "Primary source for Walmart's October 1, 1970 IPO date and $16.50 offer price.",
    accessedOn,
  },
  {
    id: "walmart-ipo-digest",
    title: "SEC News Digest, September 30, 1970",
    url: "https://www.sec.gov/news/digest/1970/dig093070.pdf",
    kind: "regulatory-filing",
    publisher: "SEC",
    note: "Primary source noting Wal-Mart Stores would have 1,300,000 common shares outstanding after the offering.",
    accessedOn,
  },
  {
    id: "open-food-network",
    title: "Open Food Network",
    url: "https://www.openfoodnetwork.org/",
    kind: "open-source-project",
    publisher: "Open Food Network",
    note: "Open, cooperative marketplace infrastructure relevant to retail decentralization.",
    accessedOn,
  },
  {
    id: "nextcloud",
    title: "Nextcloud",
    url: "https://nextcloud.com/",
    kind: "open-source-project",
    publisher: "Nextcloud",
    note: "Widely adopted self-hosted cloud platform.",
    accessedOn,
  },
  {
    id: "syncthing",
    title: "Syncthing",
    url: "https://syncthing.net/",
    kind: "open-source-project",
    publisher: "Syncthing",
    note: "Peer-to-peer sync tool relevant to iCloud replacement arguments.",
    accessedOn,
  },
  {
    id: "peertube",
    title: "PeerTube",
    url: "https://joinpeertube.org/",
    kind: "open-source-project",
    publisher: "Framasoft",
    note: "Federated video alternative relevant to YouTube.",
    accessedOn,
  },
  {
    id: "gitea",
    title: "Gitea",
    url: "https://about.gitea.com/",
    kind: "open-source-project",
    publisher: "Gitea",
    note: "Open alternative to centrally hosted developer platforms.",
    accessedOn,
  },
  {
    id: "pixelfed",
    title: "Pixelfed",
    url: "https://pixelfed.org/",
    kind: "open-source-project",
    publisher: "Pixelfed",
    note: "Federated photo-sharing alternative relevant to Instagram.",
    accessedOn,
  },
  {
    id: "matrix",
    title: "Matrix",
    url: "https://matrix.org/",
    kind: "open-source-project",
    publisher: "Matrix.org Foundation",
    note: "Open messaging protocol alternative.",
    accessedOn,
  },
  {
    id: "minio",
    title: "MinIO",
    url: "https://min.io/",
    kind: "open-source-project",
    publisher: "MinIO",
    note: "Object storage alternative relevant to cloud stacks.",
    accessedOn,
  },
  {
    id: "akash",
    title: "Akash Network",
    url: "https://akash.network/",
    kind: "open-source-project",
    publisher: "Akash Network",
    note: "Decentralized compute marketplace relevant to cloud/GPU decentralization.",
    accessedOn,
  },
  {
    id: "openevse",
    title: "OpenEVSE",
    url: "https://openevse.com/",
    kind: "open-source-project",
    publisher: "OpenEVSE",
    note: "Open charging infrastructure reference.",
    accessedOn,
  },
  {
    id: "openems",
    title: "OpenEMS",
    url: "https://openems.io/",
    kind: "open-source-project",
    publisher: "OpenEMS",
    note: "Open energy management reference.",
    accessedOn,
  },
];
